services:
  pritunl:
    image: 0fl01/pritunl-web:v1.32.4400.99.47eb68
    #build:
    #  context: .
    #  dockerfile: pritunl-web/Dockerfile
    container_name: pritunl
    privileged: true
    network_mode: host
    volumes:
      - ./pritunl_data:/var/lib/pritunl
      - /dev/net/tun:/dev/net/tun
    environment:
      - PRITUNL_MONGODB_URI=mongodb://127.0.0.1:27017/pritunl
      - PRITUNL_BIND_ADDR=0.0.0.0
      - PRITUNL_DEBUG=false
      - PRITUNL_API=127.0.0.1:8443
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3
    depends_on:
      - mongo

  pritunl-api:
    image: docker.io/0fl01/pritunl-api:0.0.2
    #build:
    #  context: .
    #  dockerfile: fake-api-server/Dockerfile
    #image: prutunl-api:bundled
    container_name: pritunl-api
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3
    ports:
      #- "80:80"
      - "127.0.0.1:8443:443"

  mongo:
    image: mongo:8.0
    container_name: pritunl-mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3

