services:
  pritunl:
    #image: 0fl01/pritunl-web:v1.32.4400.99.47eb68-full
    build:
      context: ./pritunl-web
      dockerfile: Dockerfile
    container_name: pritunl
    privileged: true
    network_mode: host
    volumes:
      - ./pritunl_data:/var/lib/pritunl
      - /dev/net/tun:/dev/net/tun
    environment:
      - PRITUNL_MONGODB_URI=mongodb://127.0.0.1:27017/pritunl
      - PRITUNL_BIND_ADDR=0.0.0.0
      - PRITUNL_DEBUG=false
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: pritunl-mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3

